### ISSUE TITLE
Impossible to disable auto comment hiding based on score 

### ISSUE THREAD

**Issue by DeeUnderscore** [QuantumBadger/RedReader#287]
Per the dialog that comes up when setting the "Minimum Comment Score" option, the option can be left blank to disable comment hiding completely. This does not seem to actually apply, though, as leaving the setting blank seems to set the threshold to -4 instead—comments below -4 score end up autohidden.

I experienced the bug with 1.9.3 on two devices, one running CM13 (Android 6.0.1), and one running CM12.1 (Android 5.1.1), reading new or previously unread posts (in case the hidden state was cached). 

(as a side note, there seem to be two duplicate issues for this feature: #58 and #268)

**Comment by QuantumBadger** [comment]
Thanks for the report. I've fixed this in v1.9.3.1, which should be released in the new few hours.

**Comment by ishults** [comment]
Dangit, sorry.  This worked when the default was "null", but with the change I didn't fix it.  Thanks @QuantumBadger.
